# Generated by Django 5.2.4 on 2025-07-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0002_producto_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="image",
            new_name="imagen",
        ),
    ]
